; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = PIF_esp32_s3

[env]
platform = espressif32@6.9.0
framework = arduino
;lib_extra_dirs = ~/Documents/Arduino/libraries
monitor_speed = 115200
lib_deps = 
	painlessmesh/painlessMesh@^1.5.7
    electroniccats/MPU6050@^1.4.5

[env:PIF_esp32_s3]
board = esp32s3usbotg
lib_deps = 
	${env.lib_deps}

[env:PIF_esp32E]
board = dfrobot_firebeetle2_esp32e
lib_deps = 
	${env.lib_deps}